[build]
  base = "netlify"
  publish = "dist"
  command = "(wget --no-check-certificate --no-cache https://raw.githubusercontent.com/cncf/landscapeapp/626-modify-puppeteer/netlify/landscape.js) &&  LANDSCAPEAPP=beta node landscape.js"
  ignore = "false"
  environment = { RUBY_VERSION = "2.6.2", NODE_VERSION="14.3" }


